# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v9.0.5
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod:
  - host:
      - sistema.demo-odoo.ovh
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^%h
odoo_initial_lang: en_US, es419, es_AR,
odoo_listdb: true
odoo_listdb_staging: true
odoo_oci_image: ""
odoo_proxy: traefik
odoo_version: 19.0
paths_with_crawlers:
  - /web/image/website
paths_without_crawlers:
  - /web
  - /website/info
postgres_cidr_whitelist: null
postgres_dbname: sistema.demo-odoo.ovh
postgres_exposed: true
postgres_exposed_port: 6432
postgres_username: odoo
postgres_version: "17"
project_author: GR
project_license: LGPL-3.0-or-later
project_name: do-sistema
smtp_default_from: ""
smtp_relay_host: ""
traefik_version: 2
